### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by mymai91** [lotus/lotus#215] opened 2015-05-03 05:31 UTC
Currently, I'm using Lotus to setup for backend, create API and use yeoman to setup for frontend (Using with AngularJS).
 I'm using port 2300 for backend & port 9000 for frontend.
I figured out a bug about `'Access-Control-Allow-Origin' header` when I try connecting both of them.

**Comment by joneslee85** [comment] 2015-05-08 02:15
@jodosha is there a way to set headers?

**Comment by jodosha** [comment] 2015-05-11 12:36
@mymai91 @joneslee85 Headers can be set globally for an application with:

```ruby
# apps/web/application.rb
controller.default_headers "X-Custom-Header" => "value"
```

If you need only for certain resources, from an action you can do:

```ruby
def call(params)
  headers["X-Custom-Header"] = "value"
end
```

**Comment by joneslee85** [comment] 2015-05-22 03:00
@mymai91 can you please try this out? I want to make sure it works, if it does, then we could do a PR to document about it. TIA

**Comment by mymai91** [comment] 2015-05-22 04:07
@joneslee85 I'll update it soon. Thanks

**Comment by mymai91** [comment] 2015-05-26 11:14
@joneslee85 @jodosha It works for now. I found a solution 
Use:
```ruby
def call(params)
    headers["Access-Control-Allow-Origin"] = '*'
    headers["Access-Control-Request-Method"] = '*' 
end
```
@joneslee85 :
I'll update example in 2 cases:
* set up frontend run directly with Lotus
* set up frontend run parallel with Lotus
I hope I will finish example in this week.

**Comment by jodosha** [comment] 2015-05-26 12:12
@mymai91 Lotus doesn't handle these headers, so the issue is actually a browser security restriction. You'll probably see that error with all the web frameworks.

I guess these values will be needed application wise, if your javascripts are included everywhere. Lotus offers this `default_headers` facility (see above) to help you in this case.

Assigning `"*"` to that headers works, but it opens the doors to attacks, as these headers were introduced for security reasons.

I strongly suggest to whitelist the origins (domains) that your application should be able to access. Eg.

```ruby
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Methods: POST, GET, OPTIONS
```

For a detailed explanation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

I'm closing this ticket as it isn't related to Lotus.

**Closed by jodosha** 2015-05-26 12:12 UTC
